from src.data_viewers.abstract.data_viewer_basic import DataViewerBasic
from src.data_viewers.text.data_text_basic import DataTextBasic
from src.data_viewers.text.data_text_value import DataViewerText