@startuml
class MyClass {
    - attribute1: type
    - attribute2: type
    + method1(): void
    + method2(): void
}

class AnotherClass {
    - attribute3: type
    + method3(): void
}

MyClass --> AnotherClass
@enduml