on: push

jobs:
  flake8:
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     python-version: ["3.11", "3.12"]

    container:
      image: cimg/python:3.11

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: poetry install

      - name: Run flake8
        run: poetry run flake8