on: push

jobs:
  flake8:
    runs-on: ubuntu-latest
    container:
      image: cimg/python:3.11

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: poetry lock [--no-update] && poetry install --only dev

      - name: Run flake8
        run: poetry run flake8


  black:
    runs-on: ubuntu-latest
    container:
      image: cimg/python:3.11

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: poetry lock [--no-update] && poetry install --only dev

      - name: Run black
        run: poetry run black --check .

  # pytest:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: cimg/python:3.11

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: recursive

  #     - name: Install dependencies
  #       run: poetry install --without dev

  #     - name: Run tests
  #       run: poetry run pytest tests/